version: "3.9"
services:
  dagster:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dagster
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DAGSTER_HOME: /app/dagster_home
    volumes:
      - ./dagster_home:/app/dagster_home  

  postgres:
    image: postgres:11
    container_name: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "54321:5432"
